version: '3.8'

services:
  frontend-profitrack:
    build:
      context: .
      args:
        REACT_APP_API_LOCAL: http://host.docker.internal:8080/api
    image: frontend-profitrack:latest
    container_name: frontend-profitrack
    restart: on-failure
    ports:
      - "3000:80"